name: Build and deploy
on : 
  workflow_dispatch:
    input:
      branch:
          name: workflow branch
          type: choice
          required: true
          options:
            - main
            - dev

      env:
        - name: environment
          type: choice
          required: true
          options:
            - prod
            - dev
            - qa


jobs:
  runs-on: ubuntu-latest
  steps:
    build:
      - name: greetings
        run: echo "hello world"