name: Build and deploy
on : 
  workflow_dispatch:
    input:
      branch:
          name: workflow branch
          type: choice
          required: true
          options:
            - main
            - dev

      env:
        - name: environment
          type: choice
          required: true
          options:
            - prod
            - dev
            - qa
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{steps.set_tag.outputs.image_tag}}
    steps:
        - name: fetch codes
          uses: actions/checkout@v3
        - name: setup node
          uses: actions/setup-node@v3
          with:
            node-version: 24
        - name: install dependencies
          run: echo "npm i"
        - name: setup docker image tag
          id: set_tag
          run: echo "image_tag=myapp:${GITHUB_SHA}" >> $GITHUB_OUTPUT
        - name: setup docker build
          uses: docker/setup-buildx-action@v3
        - name: build docker image
          run: |
            docker build -t ${{steps.set_tag.outputs.image_tag}} .


          
