name: deploy app
on: workflow_dispatch
jobs:
  test-jobs: 
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "Hello World"
      - name: print goodbye
        run: echo 'bbye'