name: deploy app
on: 
  pull_request:
    types: 
    - opened
    branches:
      - main
      - dev-*
      - feature/**
  workflow_dispatch:
    inputs:
      branch:
        description: branch workflow
        required: true
        type: choice
        options:
          - main
          - dev
          - feature/new-feature
      environment:
        descriptions: enviroment select
        required: true
        default: dev
        type: choice
        options:
          - dev
          - prod
          - qa
  push:
    branches:
      - main
      - dev-*
      - feature/**

jobs:
  test-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: get codes
        uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 24
      - name: dependency caching
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{hashFiles('**/package-lock.json')}}
      - name: install dependencies
        run: |
          npm i
          npm run build
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: next-abstract
          path:
            app
      - name: list artifact
        run: ls
  deploy:
    needs: test-jobs
    runs-on: ubuntu-latest
    steps:
      - name: print deploy greetings
        run: echo "hello deploy" 
      - name: get code
        uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v3 
      - name: dependency caching
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{hashFiles('**/package-lock.json')}}
      - name: install dependencies
        run: npm i
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: next-abstract
      - name: log the downloaded artifact
        run: ls

