name: deploy app
on: 
  pull_request:
    types: 
    - opened
  workflow_dispatch:
jobs:
  test-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: get codes
        uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 24
      - name: install dependencies
        run: npm i